### ISSUE TITLE
Config Lines and Config Sizes don't get scraped with only default groups being used

### ISSUE THREAD

**Issue by waza-ari** [akquinet/oxidized-exporter#1]
Hi, first of all, thanks for your awesome project! Using oxidized in a small non-profit environment, being able to monitor this using Grafana and Prometheus is a piece that was missing - so far it's working great!

When using Oxidized without groups (all devices attached to the default) groups, the exporter will not export the stats for `oxidized_device_config_lines` (always 0) or `oxidized_device_config_size` (always 14, probably the 404 not found reply). I believe that this is related to this request:

https://github.com/akquinet/oxidized-exporter/blob/b8f80bf4be1cde6fc602929dc09e49f9f39ba1d4/oxidized/client.go#L127

When not using groups, the URL is simply `/node/fetch/<device_name>`, there's no group in the path. `/node/fetch/default/<device_name>` yields a 404. When adding groups, the exporter works fine as is.

**Comment by rwxd** [comment]
Hi, thanks for your feedback!

I've added a condition to change the URL when all devices are configured to the group default.  Could you please try out version `v1.0.3` and let me know if it works for you?

**Comment by waza-ari** [comment]
Hi, thanks! I've added a group for our devices already, can't really test this in the existing environment anymore. However if I get the chance, I can setup a small lab to test it again.
